{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.co.infocity",
    "module": "RichFlyer",
    "version": "1.6.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "RichFlyer-1.6.4.aar",
          "url": "RichFlyer-1.6.4.aar",
          "size": 130254,
          "sha512": "3e0def82f2debc9924579359451846884f82ac1fa661849e5954350eb08f9776be07d7c3ae6773f311d6e3f82d887743de82ce11122a1c46948c05af7f91d743",
          "sha256": "9ed0666bc753025133f048c2404e2c895b0d59034d4126353617a3961576fe40",
          "sha1": "dc03663935d7bdc05b6998ca58018bbab5959bd7",
          "md5": "25d7ce16bf50acbebf5d09d8c4825a89"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.firebase",
          "module": "firebase-perf",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "RichFlyer-1.6.4.aar",
          "url": "RichFlyer-1.6.4.aar",
          "size": 130254,
          "sha512": "3e0def82f2debc9924579359451846884f82ac1fa661849e5954350eb08f9776be07d7c3ae6773f311d6e3f82d887743de82ce11122a1c46948c05af7f91d743",
          "sha256": "9ed0666bc753025133f048c2404e2c895b0d59034d4126353617a3961576fe40",
          "sha1": "dc03663935d7bdc05b6998ca58018bbab5959bd7",
          "md5": "25d7ce16bf50acbebf5d09d8c4825a89"
        }
      ]
    }
  ]
}
