{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.co.infocity",
    "module": "RichFlyer",
    "version": "1.6.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "RichFlyer-1.6.11.aar",
          "url": "RichFlyer-1.6.11.aar",
          "size": 134864,
          "sha512": "776ebf2a9faf316e328229b137899a056cb57f34e39a2d92fa67762f6f80f952411ce14f4da6f64eba533ee3b26ca709c41929ca8164b6cb919be1b7739a8896",
          "sha256": "43dacd67aebf948b71b88887a429379ba3fcb744966a6ed5dd129edd1efe943a",
          "sha1": "4352a960513e84661b10157185b94ced17d096a0",
          "md5": "39fdbbf92a29170c83ef28f1d1c21e5c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "RichFlyer-1.6.11.aar",
          "url": "RichFlyer-1.6.11.aar",
          "size": 134864,
          "sha512": "776ebf2a9faf316e328229b137899a056cb57f34e39a2d92fa67762f6f80f952411ce14f4da6f64eba533ee3b26ca709c41929ca8164b6cb919be1b7739a8896",
          "sha256": "43dacd67aebf948b71b88887a429379ba3fcb744966a6ed5dd129edd1efe943a",
          "sha1": "4352a960513e84661b10157185b94ced17d096a0",
          "md5": "39fdbbf92a29170c83ef28f1d1c21e5c"
        }
      ]
    }
  ]
}
